/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GameMechanicPrototype;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/* FrameDemo.java requires no other files. */
public class App extends JFrame {
     

}
